# ----- Projet DBT: dbt_meteoforecast -----

name: 'dbt_pipeline'
version: '1.0.0'
config-version: 2 

# --- Nom du profil utilisé ---

profile: 'profil_meteoforecast'

# --- Chemin des repertoires --- 
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

# --- Configuration des couches dbt ---
models:
  dbt_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
