version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: infoclimat
      - name: open_meteo_roubaix
      - name: weather_ichtegem_011024
      - name: weather_ichtegem_021024
      - name: weather_ichtegem_031024
      - name: weather_ichtegem_041024
      - name: weather_ichtegem_051024
      - name: weather_ichtegem_061024
      - name: weather_ichtegem_071024
      - name: weather_la_madeleine_011024
      - name: weather_la_madeleine_021024
      - name: weather_la_madeleine_031024
      - name: weather_la_madeleine_041024
      - name: weather_la_madeleine_051024
      - name: weather_la_madeleine_061024
      - name: weather_la_madeleine_071024